declare module '@eslint/js'
declare module 'eslint-plugin-import'
declare module 'eslint-plugin-unicorn'
declare module 'eslint-plugin-antfu'
declare module 'eslint-config-prettier'
declare module 'eslint-plugin-markdown'
declare module 'eslint-plugin-vue'
declare module '@unocss/eslint-plugin'
